/**
 * Livret template — generates a complete Typst document
 *
 * Produces an A4 livret with cover page, TOC, cours sections,
 * series, and footer branding.
 */

export interface LivretSection {
  label: string
  content: string // Pre-converted Typst markup for all activities in this section
}

export interface LivretData {
  title: string
  programme: string
  programmeLabel: string
  trimester: string
  objectives: string[]
  estimatedMinutes: number
  totalActivities: number
  sections: LivretSection[]
  /** Typst markup for the cover QR code (booklet pairing) */
  coverQr?: string
  /** Booklet code displayed on cover (e.g. "CONT-3E-001") */
  bookletCode?: string
  /** If true, add exam instructions after TOC (duration, calculator policy, etc.) */
  examMode?: boolean
}

export function generateLivretTypst(data: LivretData): string {
  const hours = Math.floor(data.estimatedMinutes / 60)
  const mins = data.estimatedMinutes % 60
  const timeStr = hours > 0
    ? `${hours}h${mins > 0 ? `${mins.toString().padStart(2, '0')}` : ''}`
    : `${mins} min`

  // ── Sections content ──
  const sectionsTypst = data.sections.map((section, i) => `
// ── Section ${i + 1} ──
== ${section.label}

${section.content}
`).join('\n')

  // ── Full document ──
  return `// ═══════════════════════════════════════════
// Livret eleve — ${data.title}
// Generated by learning-web pipeline
// ═══════════════════════════════════════════

#import "@preview/mitex:0.2.5": mitex, mi

// ── Page setup ──
#set page(
  paper: "a4",
  margin: (top: 25mm, bottom: 25mm, left: 20mm, right: 20mm),
  header: context {
    if counter(page).get().first() > 1 {
      set text(size: 8pt, fill: luma(150))
      [${data.title} #h(1fr) ${data.programmeLabel}]
      line(length: 100%, stroke: 0.3pt + luma(200))
    }
  },
  footer: context {
    set text(size: 8pt, fill: luma(150))
    line(length: 100%, stroke: 0.3pt + luma(200))
    v(2pt)
    [aylansolutions.com #h(1fr) #counter(page).display() #h(1fr) ${data.trimester}]
  },
)

#set text(font: "New Computer Modern", size: 10.5pt, lang: "fr", hyphenate: true)
#set par(justify: true)
#set heading(numbering: none)

// ── Custom blocks ──

#let definition(title, body) = block(
  width: 100%,
  inset: 12pt,
  stroke: (left: 3pt + rgb("#6366f1")),
  fill: rgb("#eef2ff"),
  above: 1em,
  below: 1em,
  {
    if title != none and title != [] and title != "" {
      text(weight: "bold", fill: rgb("#4338ca"))[#title]
      parbreak()
    }
    body
  }
)

#let theorem(title, body) = block(
  width: 100%,
  inset: 12pt,
  stroke: (left: 3pt + rgb("#dc2626")),
  fill: rgb("#fef2f2"),
  above: 1em,
  below: 1em,
  {
    if title != none and title != [] and title != "" {
      text(weight: "bold", fill: rgb("#b91c1c"))[#title]
      parbreak()
    }
    body
  }
)

#let property(title, body) = block(
  width: 100%,
  inset: 12pt,
  stroke: (left: 3pt + rgb("#0891b2")),
  fill: rgb("#ecfeff"),
  above: 1em,
  below: 1em,
  {
    if title != none and title != [] and title != "" {
      text(weight: "bold", fill: rgb("#0e7490"))[#title]
      parbreak()
    }
    body
  }
)

#let example-block(title, body) = block(
  width: 100%,
  inset: 12pt,
  stroke: (left: 3pt + rgb("#16a34a")),
  fill: rgb("#f0fdf4"),
  above: 1em,
  below: 1em,
  {
    if title != none and title != [] and title != "" {
      text(weight: "bold", fill: rgb("#15803d"))[#title]
      parbreak()
    }
    body
  }
)

#let remark(title, body) = block(
  width: 100%,
  inset: 12pt,
  stroke: (left: 3pt + rgb("#ca8a04")),
  fill: rgb("#fefce8"),
  above: 1em,
  below: 1em,
  {
    if title != none and title != [] and title != "" {
      text(weight: "bold", fill: rgb("#a16207"))[#title]
      parbreak()
    }
    body
  }
)

// ── Difficulty stars helper ──
#let difficulty-stars(level) = {
  let filled = "★"
  let empty = "☆"
  let stars = ""
  for i in range(3) {
    if i < level { stars += filled } else { stars += empty }
  }
  text(size: 8pt, fill: luma(120))[#stars]
}

// ── Exercise frame ──
#let exercise-frame(number, title, body, qr: none, lines: none, time: none, difficulty: none, minutes: none) = {
  // Compute number of writing lines
  let n-lines = 0
  if lines != none {
    n-lines = lines
  } else if time != none {
    if time <= 8 { n-lines = 8 }
    else if time <= 12 { n-lines = 12 }
    else { n-lines = 16 }
  } else {
    n-lines = 10
  }

  block(
    width: 100%,
    inset: 12pt,
    stroke: 0.5pt + luma(200),
    radius: 4pt,
    above: 1.2em,
    below: 1.2em,
    {
      // Header with title on first line, metadata on second line
      let meta-line = {
        if difficulty != none or minutes != none {
          v(0.2em)
          if difficulty != none { difficulty-stars(difficulty); h(0.8em) }
          if minutes != none { text(size: 8pt, fill: luma(120))[Durée : ~#minutes min] }
        }
      }

      if qr != none {
        grid(
          columns: (1fr, auto),
          column-gutter: 8pt,
          {
            text(weight: "bold")[Exercice #number — #title]
            meta-line
            parbreak()
            body
          },
          align(top, qr)
        )
      } else {
        text(weight: "bold")[Exercice #number — #title]
        meta-line
        parbreak()
        body
      }
      v(0.8em)
      // Writing lines for student
      for i in range(n-lines) {
        v(0.6em)
        line(length: 100%, stroke: 0.3pt + luma(220))
      }
      v(0.5em)
      text(size: 7.5pt, style: "italic", fill: luma(140))[Solution détaillée sur l'application — scannez le QR code]
    }
  )
}

// ── QCM frame ──
#let qcm-question(number, question, options, difficulty: none) = block(
  width: 100%,
  inset: 12pt,
  stroke: 0.5pt + luma(200),
  radius: 4pt,
  above: 1em,
  below: 1em,
  {
    {
      text(weight: "bold")[Question #number]
      if difficulty != none {
        h(1fr)
        difficulty-stars(difficulty)
      }
    }
    parbreak()
    question
    parbreak()
    v(0.3em)
    for (i, opt) in options.enumerate() {
      box(
        width: 1em,
        height: 1em,
        stroke: 1pt + luma(100),
        radius: 50%,
      )
      h(0.5em)
      opt
      parbreak()
      v(0.2em)
    }
    v(0.3em)
    text(size: 7.5pt, style: "italic", fill: luma(140))[Vérifiez vos réponses sur l'application]
  }
)

// ═══════════════════════════════════════════
// COVER PAGE
// ═══════════════════════════════════════════

#page(header: none, footer: none)[
  #v(1fr)
  #align(center)[
    #text(size: 14pt, fill: luma(120))[${data.programmeLabel}]

    #v(1em)

    #text(size: 24pt, weight: "bold")[${data.title}]

    #v(1.5em)

    #line(length: 40%, stroke: 1pt + luma(200))

    #v(1.5em)

    #text(size: 11pt, fill: luma(80))[
      ${data.totalActivities} activités  |  ${timeStr}  |  ${data.trimester}
    ]

    #v(2em)

    #block(width: 75%, inset: 16pt, stroke: 0.5pt + luma(200), radius: 6pt)[
      #align(center)[#text(weight: "bold")[Objectifs du module]]
      #v(0.5em)
      #align(left)[
        ${data.objectives.map((o, i) => `${i + 1}. ${o}`).join('\\\\\n        ')}
      ]
    ]
  ]
  #v(1.5em)

  #block(width: 75%, inset: 12pt, stroke: 0.5pt + luma(200), radius: 6pt)[
    #grid(
      columns: (1fr, 1fr),
      column-gutter: 12pt,
      row-gutter: 10pt,
      [Nom : #box(width: 1fr, repeat[.])],
      [Prénom : #box(width: 1fr, repeat[.])],
      [Classe : #box(width: 1fr, repeat[.])],
      [Année : 20#box(width: 2em, repeat[.]) / 20#box(width: 2em, repeat[.])],
    )
  ]

  #v(1fr)
  #align(center)[
    ${data.coverQr && data.bookletCode ? `
    #text(size: 9pt, fill: luma(100))[Code livret : #text(weight: "bold")[${data.bookletCode}]]
    #v(0.5em)
    #${data.coverQr}
    #v(0.5em)
    #text(size: 8pt, fill: luma(150))[Scannez pour associer ce livret]
    ` : `
    #text(size: 9pt, fill: luma(150))[Livret élève — Version énoncés]
    `}
  ]
]

// ═══════════════════════════════════════════
// TABLE OF CONTENTS
// ═══════════════════════════════════════════

#outline(title: [Sommaire], indent: 1.5em, depth: 2)

${data.examMode ? `
#v(1fr)
#block(width: 100%, inset: 14pt, stroke: 1pt + luma(180), radius: 6pt, fill: rgb("#fffbeb"))[
  #text(weight: "bold", size: 11pt)[Consignes]
  #v(0.3em)
  - *Durée indicative* : ${timeStr}
  - Toute réponse doit être *justifiée*.
  - La qualité de la rédaction est prise en compte.
  - Les exercices sont indépendants et peuvent être traités dans n'importe quel ordre.
  - Scanner le QR code de chaque exercice pour accéder à la solution détaillée.
]
#pagebreak()
` : `
#pagebreak(weak: true)
`}

// ═══════════════════════════════════════════
// COURS
// ═══════════════════════════════════════════

= ${data.title}

${sectionsTypst}

// ═══════════════════════════════════════════
// NOTES PAGE
// ═══════════════════════════════════════════

#pagebreak()

== Notes

#v(1em)

#for i in range(30) {
  v(0.7em)
  line(length: 100%, stroke: 0.3pt + luma(200))
}

`
}
