/**
 * Livret template — generates a complete Typst document
 *
 * Produces an A4 livret with cover page, TOC, cours sections,
 * series, and footer branding.
 */

export interface LivretSection {
  label: string
  content: string // Pre-converted Typst markup for all activities in this section
}

export interface LivretSerie {
  title: string
  description: string
  difficulty: number
  content: string // Pre-converted Typst markup
}

export interface LivretData {
  title: string
  programme: string
  programmeLabel: string
  trimester: string
  objectives: string[]
  estimatedMinutes: number
  totalActivities: number
  sections: LivretSection[]
  series: LivretSerie[]
  /** Typst markup for the cover QR code (booklet pairing) */
  coverQr?: string
  /** Booklet code displayed on cover (e.g. "CONT-3E-001") */
  bookletCode?: string
}

function difficultyStars(level: number): string {
  const filled = '#sym.star.filled '.repeat(level)
  const empty = '#sym.star '.repeat(3 - level)
  return `[${filled}${empty}]`
}

export function generateLivretTypst(data: LivretData): string {
  const hours = Math.floor(data.estimatedMinutes / 60)
  const mins = data.estimatedMinutes % 60
  const timeStr = hours > 0
    ? `${hours}h${mins > 0 ? `${mins.toString().padStart(2, '0')}` : ''}`
    : `${mins} min`

  // ── Sections content ──
  const sectionsTypst = data.sections.map((section, i) => `
// ── Section ${i + 1} ──
== ${section.label}

${section.content}
`).join('\n')

  // ── Series content ──
  const seriesTypst = data.series.length > 0
    ? data.series.map((serie, i) => `
#pagebreak()

// ── Serie ${i + 1} ──
= Serie : ${serie.title}

#text(size: 9pt, fill: luma(100))[${serie.description}] #h(1fr) Difficulte : ${difficultyStars(serie.difficulty)}

#v(0.5em)

${serie.content}
`).join('\n')
    : ''

  // ── Full document ──
  return `// ═══════════════════════════════════════════
// Livret eleve — ${data.title}
// Generated by learning-web pipeline
// ═══════════════════════════════════════════

#import "@preview/mitex:0.2.5": mitex, mi

// ── Page setup ──
#set page(
  paper: "a4",
  margin: (top: 25mm, bottom: 25mm, left: 20mm, right: 20mm),
  header: context {
    if counter(page).get().first() > 1 {
      set text(size: 8pt, fill: luma(150))
      [${data.title} #h(1fr) ${data.programmeLabel}]
      line(length: 100%, stroke: 0.3pt + luma(200))
    }
  },
  footer: context {
    set text(size: 8pt, fill: luma(150))
    line(length: 100%, stroke: 0.3pt + luma(200))
    v(2pt)
    [learning.app #h(1fr) #counter(page).display() #h(1fr) ${data.trimester}]
  },
)

#set text(font: "New Computer Modern", size: 10.5pt, lang: "fr")
#set par(justify: true)
#set heading(numbering: none)

// ── Custom blocks ──

#let definition(title, body) = block(
  width: 100%,
  inset: 12pt,
  stroke: (left: 3pt + rgb("#6366f1")),
  fill: rgb("#eef2ff"),
  above: 1em,
  below: 1em,
  {
    if title != none and title != [] and title != "" {
      text(weight: "bold", fill: rgb("#4338ca"))[#title]
      parbreak()
    }
    body
  }
)

#let theorem(title, body) = block(
  width: 100%,
  inset: 12pt,
  stroke: (left: 3pt + rgb("#dc2626")),
  fill: rgb("#fef2f2"),
  above: 1em,
  below: 1em,
  {
    if title != none and title != [] and title != "" {
      text(weight: "bold", fill: rgb("#b91c1c"))[#title]
      parbreak()
    }
    body
  }
)

#let property(title, body) = block(
  width: 100%,
  inset: 12pt,
  stroke: (left: 3pt + rgb("#0891b2")),
  fill: rgb("#ecfeff"),
  above: 1em,
  below: 1em,
  {
    if title != none and title != [] and title != "" {
      text(weight: "bold", fill: rgb("#0e7490"))[#title]
      parbreak()
    }
    body
  }
)

#let example-block(title, body) = block(
  width: 100%,
  inset: 12pt,
  stroke: (left: 3pt + rgb("#16a34a")),
  fill: rgb("#f0fdf4"),
  above: 1em,
  below: 1em,
  {
    if title != none and title != [] and title != "" {
      text(weight: "bold", fill: rgb("#15803d"))[#title]
      parbreak()
    }
    body
  }
)

#let remark(title, body) = block(
  width: 100%,
  inset: 12pt,
  stroke: (left: 3pt + rgb("#ca8a04")),
  fill: rgb("#fefce8"),
  above: 1em,
  below: 1em,
  {
    if title != none and title != [] and title != "" {
      text(weight: "bold", fill: rgb("#a16207"))[#title]
      parbreak()
    }
    body
  }
)

// ── Exercise frame ──
#let exercise-frame(number, title, body, qr: none) = block(
  width: 100%,
  inset: 12pt,
  stroke: 0.5pt + luma(200),
  radius: 4pt,
  above: 1.2em,
  below: 1.2em,
  {
    if qr != none {
      grid(
        columns: (1fr, auto),
        column-gutter: 8pt,
        {
          text(weight: "bold")[Exercice #number — #title]
          parbreak()
          body
          v(5em)
        },
        align(top, qr)
      )
    } else {
      text(weight: "bold")[Exercice #number — #title]
      parbreak()
      body
      v(5em)
    }
  }
)

// ── QCM frame ──
#let qcm-question(number, question, options) = block(
  width: 100%,
  inset: 12pt,
  stroke: 0.5pt + luma(200),
  radius: 4pt,
  above: 1em,
  below: 1em,
  {
    text(weight: "bold")[Question #number]
    parbreak()
    question
    parbreak()
    v(0.3em)
    for (i, opt) in options.enumerate() {
      box(
        width: 0.8em,
        height: 0.8em,
        stroke: 0.8pt + luma(100),
        radius: 50%,
      )
      h(0.5em)
      opt
      parbreak()
    }
  }
)

// ═══════════════════════════════════════════
// COVER PAGE
// ═══════════════════════════════════════════

#page(header: none, footer: none)[
  #v(1fr)
  #align(center)[
    #text(size: 14pt, fill: luma(120))[${data.programmeLabel}]

    #v(1em)

    #text(size: 28pt, weight: "bold")[${data.title}]

    #v(1.5em)

    #line(length: 40%, stroke: 1pt + luma(200))

    #v(1.5em)

    #text(size: 11pt, fill: luma(80))[
      ${data.totalActivities} activites  |  ${timeStr}  |  ${data.trimester}
    ]

    #v(2em)

    #block(width: 70%, inset: 16pt, stroke: 0.5pt + luma(200), radius: 6pt)[
      #text(weight: "bold")[Objectifs du module]

      ${data.objectives.map(o => `+ ${o}`).join('\n      ')}
    ]
  ]
  #v(1fr)
  #align(center)[
    ${data.coverQr && data.bookletCode ? `
    #text(size: 9pt, fill: luma(100))[Code livret : #text(weight: "bold")[${data.bookletCode}]]
    #v(0.5em)
    #${data.coverQr}
    #v(0.5em)
    #text(size: 8pt, fill: luma(150))[Scannez pour associer ce livret]
    ` : `
    #text(size: 9pt, fill: luma(150))[Livret eleve — Version enonces]
    `}
  ]
]

// ═══════════════════════════════════════════
// TABLE OF CONTENTS
// ═══════════════════════════════════════════

#outline(title: [Sommaire], indent: 1.5em, depth: 2)
#pagebreak()

// ═══════════════════════════════════════════
// COURS
// ═══════════════════════════════════════════

= ${data.title}

${sectionsTypst}

// ═══════════════════════════════════════════
// SERIES
// ═══════════════════════════════════════════
${seriesTypst}
`
}
